URL_PKG_findlib = http://download.camlcity.org/download/findlib-1.5.5.tar.gz
MD5_PKG_findlib = 703eae112f9e912507c3a2f8d8c48498

URL_PKG_camlp4 = https://github.com/ocaml/camlp4/archive/4.02+6.tar.gz
MD5_PKG_camlp4 = 5bf758bb799e7a5ef9cad9cd1df91053

URL_extlib = http://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz
MD5_extlib = 3de5f4e0a95fda7b2f3819c4a655b17c

URL_PKG_extlib = http://ocaml-extlib.googlecode.com/files/extlib-1.6.1.tar.gz
MD5_PKG_extlib = 5643237a6410dc915347956cff97df86

URL_re = https://github.com/ocaml/ocaml-re/archive/ocaml-re-1.2.0.tar.gz
MD5_re = 5cbfc137683ef2b0e91f931577f2e673

URL_PKG_re = https://github.com/ocaml/ocaml-re/archive/ocaml-re-1.4.1.tar.gz
MD5_PKG_re = 20a0194ab9613f434fdfdf947f5b6d71

URL_cmdliner = http://erratique.ch/software/cmdliner/releases/cmdliner-0.9.7.tbz
MD5_cmdliner = 46d7553b95f623f811df2a844fb448fb

$(call PKG_SAME,cmdliner)

URL_graph = http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.5.tar.gz
MD5_graph = 75dde65bfc3f9b07e795343d369aa84d

URL_PKG_graph = http://ocamlgraph.lri.fr/download/ocamlgraph-1.8.6.tar.gz
MD5_PKG_graph = afbc24f0e0eb72c2d3eda64b68513e73

URL_cudf = https://gforge.inria.fr/frs/download.php/file/33593/cudf-0.7.tar.gz
MD5_cudf = 2047222fcf78278c6a24ac619fc39abb
ALTURL_cudf = http://opam.ocaml.org/archives/cudf.0.7+opam.tar.gz
ALTMD5_cudf = b12d933a96bd326e2443241faca7aa8c

URL_PKG_cudf = https://gforge.inria.fr/frs/download.php/file/34659/cudf-0.8.tar.gz
MD5_PKG_cudf = abf34d3daedd81580b7b32a871341b2f

URL_dose = https://gforge.inria.fr/frs/download.php/file/34277/dose3-3.3.tar.gz
MD5_dose = ea947804c636059bb8b64dbda5c1df08
ALTURL_dose = http://opam.ocaml.org/archives/dose.3.3+opam.tar.gz
ALTMD5_dose = 6c14696d8ab24fb88c1e592b8518c48a

$(call PKG_SAME,dose)

URL_uutf = http://erratique.ch/software/uutf/releases/uutf-0.9.3.tbz
MD5_uutf = 708c0421e158b390c7cc341f37b40add

URL_PKG_uutf = http://erratique.ch/software/uutf/releases/uutf-0.9.4.tbz
MD5_PKG_uutf = bf5880a8f2e75d0a9152d896ea288ba7

URL_jsonm = http://erratique.ch/software/jsonm/releases/jsonm-0.9.1.tbz
MD5_jsonm = 631a5dabdada83236c83056f60e42685

$(call PKG_SAME,jsonm)
